/**
 * M11-03 — the multi-node workflow DRAFT model for the wizard's 高级
 * (advanced) face: a tiny pure layer between the form state and the POST
 * /api/v1/runs body.
 *
 * Discipline: the SERVER re-validates everything (multi-node.ts's typed
 * 400 carriers are the authority). This layer's job is the 人话预检 — the
 * same v1 rules the server enforces, checked before the round trip so the
 * common mistakes surface instantly in product language:
 *   - node budget: 1..64 nodes when a workflow is declared (v1 graph budget);
 *   - every node needs a non-blank objective;
 *   - an integration node needs ≥1 dependency (the parents it merges);
 *   - a review node needs EXACTLY one dependency and the reviewer role;
 *   - at most ONE integration node per task (the v1 restriction, stated in
 *     the product sentence the server itself uses).
 * Cycles/duplicate ids/unknown dependencies are NOT preflighted here: ids
 * are generated by this layer (unique by construction) and dependencies are
 * chosen from a closed checkbox list (unknown ids impossible); the server
 * remains the authority for everything else.
 */
import type { CreateRunWorkflowNode } from "./api";

export type WorkflowDraftKind = "agent" | "integration" | "review";
export type WorkflowDraftRole = "coordinator" | "architect" | "developer" | "reviewer";

export interface WorkflowDraftNode {
  /** Client-minted, unique by construction (node-<index>-<random>). */
  readonly id: string;
  readonly role: WorkflowDraftRole;
  readonly kind: WorkflowDraftKind;
  readonly objective: string;
  /** Ids of OTHER declared nodes this node waits for. */
  readonly dependencies: readonly string[];
}

/** The frozen v1 budget (the dag default the server aligns with). */
export const WORKFLOW_NODE_BUDGET = 64;

/** Fresh client-minted node id (the server's IdSchema: ^[a-z][a-z0-9_-]{0,63}$). */
export function freshDraftNodeId(): string {
  const random = Math.random().toString(36).slice(2, 8);
  return `node-${random}`;
}

/** Human names for the three dispatch kinds (the select's labels). */
export function kindLabel(kind: WorkflowDraftKind): string {
  switch (kind) {
    case "agent":
      return "执行节点(Agent 完成一项工作)";
    case "integration":
      return "集成节点(合并各分支成果,每任务至多一个)";
    case "review":
      return "评审节点(评审一个已完成的节点)";
  }
}

/** Human names for the four built-in roles (consistent with the setup card). */
export function roleLabel(role: WorkflowDraftRole): string {
  switch (role) {
    case "coordinator":
      return "协调";
    case "architect":
      return "架构";
    case "developer":
      return "开发";
    case "reviewer":
      return "评审";
  }
}

/**
 * The 人话预检. Empty input = no workflow declared (the single-node face) —
 * valid by definition. Returns the problems in product language, in a
 * stable order (budget → per-node shape → integration count); an empty
 * array means the draft may be submitted.
 */
export function validateWorkflowDraft(nodes: readonly WorkflowDraftNode[]): readonly string[] {
  if (nodes.length === 0) return [];
  const problems: string[] = [];
  if (nodes.length > WORKFLOW_NODE_BUDGET) {
    problems.push(
      `节点数超上限:当前 ${String(nodes.length)} 个,一个任务最多 ${String(WORKFLOW_NODE_BUDGET)} 个节点。`
    );
  }
  const byId = new Set(nodes.map((node) => node.id));
  for (const node of nodes) {
    if (node.objective.trim() === "") {
      problems.push("每个节点都需要一句话目标(有节点目标为空)。");
      break; // one sentence covers the class; per-node noise helps nobody
    }
  }
  for (const node of nodes) {
    const waitingOn = node.dependencies.filter((dependency) => dependency !== node.id && byId.has(dependency));
    if (node.kind === "integration" && waitingOn.length < 1) {
      problems.push("集成节点至少要依赖一个其他节点(它是来合并其他节点成果的)。");
    }
    if (node.kind === "review") {
      if (waitingOn.length !== 1) {
        problems.push("评审节点必须且只能依赖一个节点(它评审那个节点的成果)。");
      }
      if (node.role !== "reviewer") {
        problems.push("评审节点的角色必须是「评审」。");
      }
    }
  }
  const integrationCount = nodes.filter((node) => node.kind === "integration").length;
  if (integrationCount > 1) {
    problems.push("当前版本每个任务支持一个集成节点;链式/并行集成将在后续版本支持。");
  }
  return problems;
}

/**
 * Build the request-face workflow nodes (the exact allowlist POST /api/v1/runs
 * accepts per node). Returns null when nothing is declared (single-node run).
 */
export function workflowToRequest(nodes: readonly WorkflowDraftNode[]): readonly CreateRunWorkflowNode[] | null {
  if (nodes.length === 0) return null;
  return nodes.map((node) => ({
    id: node.id,
    role: node.role,
    kind: node.kind,
    objective: node.objective.trim(),
    dependencies: [...node.dependencies]
  }));
}
